### ISSUE TITLE
Support for multiple key pairs 

### ISSUE THREAD

**Issue by dadofsambonzuki** [vitorpamplona/amethyst#104]
It would be cool to have multiple key-pairs (accounts) supported with fast switching.

🤙

**Comment by improvethings** [comment]
I just had the same idea, it could be great to ensure there are good visual cues to ensure one is posting from the proper profile (different coloured profile/banner image)

**Comment by maxmoney21m** [comment]
@vitorpamplona any ideas here for the UI/flow? Can we just save multiple private keys in the encrypted storage with some basic info (name, avatar URL), put a switcher button somewhere and just effectively do a logout/login automatically?

I would like this feature as well.

**Comment by maxmoney21m** [comment]
I'm not ready for a PR yet but some feedback would be good. Here's my idea:

![image](https://user-images.githubusercontent.com/124794312/224491543-d9307b2b-faa9-46bb-8b93-cf5e401163c8.png)

![image](https://user-images.githubusercontent.com/124794312/224491554-ab6fba99-b23e-4f28-800f-9de21354db1c.png)

To get this to work, I modified `LocalPreferences` to use keys beginning with the `npub` of the account they belong to. So instead of the preference key being something like `nostr_privkey`, now it is `npub1qqq.../nostr_privkey`. I also save the user's profile name and avatar URL in the local preferences, as well as the currently "logged in" user's npub (so that we can load the correct account when the app launches).

Then to show this account switcher, we just pull out all of the `.../nostr_pubkey` keys and look up their respective usernames and avatars. The check mark denotes the currently logged in account (in the screenshot though there is only one right now, because I did not implement the "Add New Account" screen yet).

From the account switcher screen you can either click the name/avatar to log in, or the log out button to remove that data from your device.

@vitorpamplona WDYT?

**Comment by maxmoney21m** [comment]
Alright, this is now [fully functional](https://github.com/vitorpamplona/amethyst/commit/77bea0a311096ef9a66f575a11520c7182515e73). It just needs some cleanup and should be ready for a PR, I think.

![image](https://user-images.githubusercontent.com/124794312/224506068-a60b3c03-1c88-44a8-accf-0d6acbe68033.png)

**Comment by maxmoney21m** [comment]
> I dont know if best practice is to input your private keys from client to client. I think some would be hesitant to do this, reducing prospective Amethyst users.

Android's encrypted keystore is probably one of the safest places you can put your keys. But you can also use a pubkey if you want read-only. I think using a separate signer is going to be a later issue, not able to do it right now.
