### ISSUE TITLE
[FEATURE] Have an option on settings to enable delete notes

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#1067]
Hi,

I would like to see an option on Amethyst settings to allow delete notes. When this option is marked, we will be sure that when we request to delete events will work, but how? Amethyst will verify in which relays we are connected, see if we are connected on relays that doesn't support delete Nip, and remove this relays from the user profile.

Thanks.

**Comment by vitorpamplona** [comment]
It's impossible for us to know if the relay is complying or not with deletion requests. Most of them don't actually delete, they just mark as hidden internally. But the post is still there if you find the filter that works. 

The right way to solve this is to talk to your relay operators and ask if they are deleting or not. Ideally they should put that information in their Privacy Policy/ToS and be legally liable if it doesn't happen in the way they described.

We should empower users to choose and evaluate these days. Tech cannot solve this by itself.

**Comment by bitcoinuser** [comment]
Hum, didn't know. Thanks

**Comment by git-3000** [comment]
wow this is some crazy information. I bet many don't know this. 
I think the relay software definitely needs updating. It seems the relay developers aren't that involved in the relay software.

I suspected something when my drafts kept appearing even after deleting them. I think it was the primal relay not deleting them.

I hope in the future we can have a section to send requests and see which relays are not deleting our notes. I tired the relay software is i deleting a note and the relay didn't delete it because there was a glitch in it. I had to manually go into the sql and delete it.

So its also possible that it's not the relay administrator's fault
