### ISSUE TITLE
[BUG] Amethyst doesn't seem to send Kind 10000 NIP-51 events (mute list)

### ISSUE THREAD

**Issue by ghost** [vitorpamplona/amethyst#1136]
**Describe the bug**

I am using both [Nostrudel](https://nostrudel.ninja) and Amethyst for my npub. I have noticed several times that when I mute someone on Nostrudel, it sends a Kind 10000 event with the updated list JSON data and all the relays accept it; that user then shows up in Amethyst mutes when I later refresh.

However, the reverse is does not seem to work / be true; if I mute a user in Amethyst it's saved in the app, however when I later go back to Nostrudel that user is missing from the mute list. I have to manually add them in Nostrudel to broadcast the updated NIP-51 Kind 10000 event again. I'm unsure how to see raw JSON event data in Amethyst like I can in Nostrudel to provide better information at this point.

**To Reproduce**

1. Have a Mute list in both Nostrudel and Amethyst working
2. Mute a user on Nostrudel, check Amethyst for updated mute list (OK)
3. Mute a user on Amethyst, check Nostrudel for updated mute list (NOT OK)
4. Be sad because I can't see raw events in Amethyst to do better debugging for this bug report, however I have experienced the behaviour multiple times

**Expected behavior**

Muted list propagation upstream from Amethyst to relays via an updated Kind 10000 event per NIP-51

**Device (please complete the following information):**

 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 6a
 - Android Version [e.g. 33]: 14 Stock Google ROM
 - App Version [e.g. v0.20.3]: v0.91.0-FDROID
 - Amber Version (if using it to sign): n/a

Thank you for your time.

**Comment by davotoula** [comment]
I could reproduce the issue between coracle and amethyst.

Have you tried a third client to see it the coracle muted users show up?

**Comment by vitorpamplona** [comment]
Amethyst will always and only use private lists to save mutes because saving them publically is a huge privacy issue. Many clients don't implement the full NIP and thus won't see those mutes. It's up to them to implement the NIP. 

Primal and Nostrudel don't fully implement NIP-51, so it's really up to them to finish what they started. 

> I think it has something to do with a muted word being in someone's About/Bio

Yes, mute words consider everything related to the user + the post. If you muted a word that is written in the author's about me page in his/her profile, you won't see any post by that person.
