### ISSUE TITLE
[BUG] Follows list got reset

### ISSUE THREAD

**Issue by kirillkovalenko** [vitorpamplona/amethyst#123]
It looks like that there is some kind of concurrency bug.

I followed 100+ contacts and I was adding some new contacts. Suddenly my contacts reset to only those I added last minute and the rest is gone.

**Comment by lkblkb** [comment]
Same issue, all follows gone after upgrade to 0.15.3 😭

**Comment by vitorpamplona** [comment]
This usually happens when you change relays before your contact list is downloaded from relays. Since relays and contacts are in the same Nostr message, when you save one you override the other. :( 

Same would happen if you follow/unfollow somebody before your relays list is downloaded. You would override your relay setup back to the default settings. 

And since relays don't store past versions of the contact/relay list (they could) there is no way to go back :(

**Comment by lkblkb** [comment]
Oh shoot, ya retracing my steps I *did* replace all the relays because I wanted the "paid relays for global" thing and it wasn't happening on its own for some reason. I also read that Amethyst had separate relay lists for global and other things but er ... somehow I guess I replaced the "other things" list. In fact I have never seen a global channel or a separate relay list for it. Annnnnyway appreciate the work being done and excited for the future!

**Comment by vitorpamplona** [comment]
So, it's all in the same list. Any change to that Global/Not Global setting before download follows could cause this. :(

**Comment by kirillkovalenko** [comment]
> This usually happens when you change relays list setup before your contact list is downloaded from relays. Since relays and contacts are in the same Nostr message, when you save one you override the other. :(

I haven't edited relays for a week or something already. 

Speaking of relays... I have noticed that relay view is quite chaotic. First of all, the total amount of relays may differ between the runs. For example it says m/19 in the morning, then n/15 in the day, and k/16 in the evening. Maybe I got it wrong, but my understanding is that the first number is amount of relays currently responding and the second number is the total amount of relays that amethyst uses. The second issue I've seen is that when I open relays list the amount of relays I see here does correspond to the total amount of relays it displays in the top right corner. 
 
> The app could save a local cache of the follows/relays. But then it would still override to the cache position, erasing the latest changes from other clients since the last use of the app.

Can you disable follow / unfollow until you get information from relay(s)?

> I have not found a good solution for this problem yet.

What would say about an idea of introducing an application option to declare 'This app is my profile master'? Upon option activation, the app fetches and caches profile information (and notes too?) from relay(s) of choice info a local database. Once the option has been activated, all the follow/unfollow events update the local database only and then the 'master state' is lazily pushed to relays on timer or / and manually.

**Comment by vitorpamplona** [comment]
I think this item has been fully resolved. Clearing the list can still happen but it is super rare right now.
