### ISSUE TITLE
issues when text is RTL 

### ISSUE THREAD

**Issue by rashedswen** [vitorpamplona/amethyst#184]
https://github.com/vitorpamplona/amethyst/blob/da9027b430fdd7877e5ea7d135d9d9ea28253656/app/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt#L135

when text is RTL it display like it mirroring cause each word is separate composable and can't support text direction

**Comment by vitorpamplona** [comment]
Hey @rashedswen can you check if your solution is working? I had to remove your `CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl)` because it was aligning English to the right side. 

Check here: https://github.com/vitorpamplona/amethyst/commit/ea905ef6edea2369d8db5f4c30375bced68f00d8

**Comment by rashedswen** [comment]
not working well it's appear LTR but not big deal cause even with it only one paragraph appear RTL I need to figure out something else

**Comment by vitorpamplona** [comment]
I think we have mostly fixed this RTL issues. Let me know if this still happens.
