### ISSUE TITLE
Relay icon: change request [FEATURE]

### ISSUE THREAD

**Issue by 3j2009** [vitorpamplona/amethyst#188]
Relays are such an integral part of NOSTR. I believe their importance justifies an icon that represents their network properties in an intuitive, aesthetic manner. 

I'd like to propose the below icon which shows a network of relays.

Available colors:
- Amethyst
- Precious Amethyst
- Default Grey

**_Screenshot with relay icon Amethyst_**
![Relay Icon screenshot amethyst](https://user-images.githubusercontent.com/126127093/222875626-1a2d5cdf-61fe-44a8-9c9c-5f7914f6c4ab.png)

_**Amethyst.svg**_
![Relay Icon Amethyst](https://user-images.githubusercontent.com/126127093/222875632-1422d213-2a01-452f-a072-f0d4367caf4a.svg)

_**Amethyst.png**_
![Relay Icon Amethyst](https://user-images.githubusercontent.com/126127093/222875639-59a181dc-405f-4b5e-815b-f4382647620c.png)

**_Screenshot with relay icon Precious Amethyst_**
![Relay Icon screenshot precious amethyst](https://user-images.githubusercontent.com/126127093/222875593-93b3d399-4975-4369-b7e9-133a3e6d9640.png)

_**Precious Amethyst.svg**_
![Relay Icon Precious Amethyst](https://user-images.githubusercontent.com/126127093/222875608-e7629552-ef53-4d25-90a5-1b8bfa4aa8fd.svg)

_**Precious Amethyst.png**_
![Relay Icon Precious Amethyst](https://user-images.githubusercontent.com/126127093/222875619-1c95948a-3659-4fbb-b96b-25f09ad8a005.png)

**_Screenshot with relay icon Default Grey_**
![Relay Icon screenshot grey](https://user-images.githubusercontent.com/126127093/222873386-ac22d078-ef07-4845-a0e4-2b78ab7546a1.png)

**_Default Grey.svg_**
![Relay Icon grey](https://user-images.githubusercontent.com/126127093/222875365-8893f3ef-8e70-47f9-81c3-653c9bada74c.svg)

**_Default Grey.png_**
![Relay Icon grey](https://user-images.githubusercontent.com/126127093/222873318-6d5cd861-7bdc-4517-961c-a4d9afda1575.png)

**Comment by maxmoney21m** [comment]
Nice icon. I don't know if Vitor wants to use it but I would propose:

- Flat purple instead of shading
- Slightly compressed horizontally, if possible (it feels a little too wide, IMO)
- Line thickness same as the bottom bar icons; currently it looks the same as the note action icons, which are a bit thinner due to being smaller

**Comment by 3j2009** [comment]
@maxmoney21m great feedback, thank you :)

I've thickened and compressed it (horizontally) slightly as you suggested.

2 variations with the above changes are attached below:
- Flat purple
- Default grey


![Relay Icon Flat Purple](https://user-images.githubusercontent.com/126127093/222935359-2e2ecc69-0c49-4e20-a2bc-d889e16c11d7.svg)

![Relay Icon Screenshot Flat Purple](https://user-images.githubusercontent.com/126127093/222935357-613dc0ec-0d2f-4150-b10a-8aee3e3e8cf7.png)

![Relay Icon grey #2](https://user-images.githubusercontent.com/126127093/222935360-dc371f31-2e72-4acb-bc9c-9716a04c2d3c.svg)

**Comment by maxmoney21m** [comment]
I happened to notice the “[Hub](https://fonts.google.com/icons?icon.query=hub&selected=Material+Symbols+Outlined:hub:FILL@0;wght@400;GRAD@0;opsz@48)” icon as part of the material design pack. It's not exactly the same but similar concept. Since it looks like #200 will have the Relays button moving to the Drawer which is all material icons, it might be better to use the Hub icon for consistency.

I'll try both and post screenshots here.
