### ISSUE TITLE
Move Search to the top Navigation bar?

### ISSUE THREAD

**Issue by vitorpamplona** [vitorpamplona/amethyst#200]
Now that the icon for the Global feed has been fixed. The search bar doesn't really make much sense in there. I wonder if we should do what Gmail does, a search up top, and when the user clicks, it opens a dialog for input and response. 

That would work well to find users in DMs and log into new Chats in the same field. 

What do you think?

**Comment by maxmoney21m** [comment]
I agree the search needs to be available throughout the app, but I'm wondering if we solved the problem backwards.

Maybe instead of fixing the global feed icon at the bottom, we should have moved the global feed entirely into the Home section and left search in place (but without the global feed, of course). That would make the Home tab the place to go for all the feeds, e.g. Home tab would have 3 tabs now: Threads, Conversations, Global. Could be expandable in the future with custom lists, etc. I can imagine that eventually global might be removed anyway if there is so much content that it's useless to even try.

**Comment by vitorpamplona** [comment]
The problem with merging Global and Home is that the relay set for them is completely different. We will move to a model where global will likely have a relay of choice while Home will use any relay your follows are writing to (the relay list is gone). 

But search is ubiquitous. And it would use a separate relay set from everything else.

**Comment by maxmoney21m** [comment]
What is the relationship between the relay set of a feed and which feed the screen is on? Currently I see that the data source is picked in the `___Screen` Composable, but could that not be pushed down into the views under the `HorizontalPager`?

**Comment by vitorpamplona** [comment]
Screens start DataSource filters (Singletons) that will trigger relays sending data based on where the screen is at and saving it on the LocalCache.

At the same time, Screens re-initialize DAL Filters to pull from the LocalCache into a ViewModel. Those DAL Filters are also Singletons (just because I am too dumb to understand how ViewModel custom factories / lifecycle works) and each ViewModel default constructor links to a filter. 

Terrible design, but I was having way too many memory leaks with Android reusing ViewModels in the past.

**Comment by maxmoney21m** [comment]
@vitorpamplona please check: https://github.com/maxmoney21m/amethyst/blob/test/global-on-home/app/src/main/java/com/vitorpamplona/amethyst/ui/screen/loggedIn/HomeScreen.kt

This works great for me so far, just testing it out.

If you like it, the branch needs some more work to fix the Search screen (which would now be for actual Search, rather than the Global feed). I can PR it into a separate branch so someone else can work on that, or maybe I can do it later.

![image](https://user-images.githubusercontent.com/124794312/222980185-8b8ecaa3-f6bb-4c0e-b7ca-35ed94d1e512.png)

**Comment by vitorpamplona** [comment]
I don't know.. this feels like it goes back in time for me and it probably focuses users on the home tab way too much (I don't like the idea of a "home" tab users go back to). 

The long-term view is to have: 
1. Home for follows, new threads and on-going conversations, 
2. A new tab for a Slack-type of relay-bound per-topic interfaces based on Public Chats
3. Private DMs and Private Group messages combined, separated by known and new requests, 
4. Global with a choice of relay with 2 tabs: hot and latest
5. Notifications.

**Comment by maxmoney21m** [comment]
That actually makes sense, so the divisions are kind of like:

1. People / public discussions
2. Topics / focused discussions
3. Private
4. Discovery
5. Notifications

In that case I think it's, especially if the Global / Discovery screen is going to get more options for some kind(s) of algorithmic sorting. (I maintain that full global raw feed will eventually be more or less useless, so algorithms will be needed, and different options would be cool for that.)

Back to your original question then, do you mean that Search would get an icon in the top bar (next to the relay button or PFP)? I think it would be best to display a proper screen rather than a dialog, but it's fine if it's accessed from the top. Search results should probably also be tabbed for Users and Notes at least, right now they seem to be mixed in together.

**Comment by vitorpamplona** [comment]
> do you mean that Search would get an icon in the top bar (next to the relay button or PFP)

That's what I was thinking, but I am open to new ideas. 

> proper screen rather than a dialog

Yep, I think in the long term we want to move from Dialogs to screens and have proper navigation between them. 

> tabbed for Users and Notes at least

There is also a Channels list

The order of results is bad right now. We need to figure out a way to get a match score (matching names goes higher than matching content)

**Comment by braydonf** [comment]
The stars icon for "Relays" at the top right isn't clear. It was associated with switching feed views (with Twitter), which also wasn't very clear. 

The Relays could move to the side pane, next to Security Filters, Profile and Backup Keys.

That space could then be for "search" or adding new public keys, which as common action.

**Comment by 3j2009** [comment]
> The stars icon for "Relays" at the top right isn't clear. It was associated with switching feed views (with Twitter), which also wasn't very clear.

I agree with this and proposed an icon change in Issue #188 

> The Relays could move to the side pane, next to Security Filters, Profile and Backup Keys.

I like this idea.


Overall i think relays need far more explanatory material for new users. Where to find new relays and which relays to choose are among the top questions I had when first starting, and in part still have now.

**Comment by maxmoney21m** [comment]
The relays screen could just get a ? icon which provides some information in a dialog, including the icon legend, suggestions, etc.

**Comment by vitorpamplona** [comment]
Take a look at Mastodon (create new user in the app).. they have an amazing
set of onboarding materials that would be similar to a Nostr relay choice.

**Comment by maxmoney21m** [comment]
@3j2009 that list of relays is huge. It wouldn't make sense to add all of them, or to randomly pick them.

Relays are complicated, probably more so than Mastodon. Each users needs different relays or sets of relays for different purposes. Hopefully part of the answer will come through the gossip NIP ([NIP-65](https://github.com/nostr-protocol/nips/blob/master/65.md)). If many clients implement this NIP, it would probably be possible to find the posts of people you follow without configuring any relays.

The main needs for manual configuration are setting your global feed and using any paid relays. At least some manual configuration will always be needed as far as I can tell. We should just strive to make it as easy as possible for newcomers.

Yes we can display relay info, we can see at least:

- Which features the relay supports
- Latency / speed for you to reach the relay
- The npub of the relay operator
- How much it costs, if paid (I think)

I'm not sure if we can pay directly in the app. If not, we can at least provide an easy path like: automatically copy the user's npub and open the relay website, user should paste it and pay the invoice. We can provide textual explanation to help make that clear.

**Comment by maxmoney21m** [comment]
@vitorpamplona would it be acceptable for a first pass PR if I do:

- Move relay button to drawer
- Move search icon to top right (all screens)
- Search icon goes to Search screen, without global feed, so initially a blank screen just with some text telling the user what things they can search for

This would not include doing different searches specific to the page the user is on, like finding a DM or chat room as you mentioned. So no new features, just rearranging the existing stuff.

**Comment by vitorpamplona** [comment]
Would you also move the x/x relay connection status? Are we ready for it? I think we still see too many little bugs and the status icon does let people know when something is wrong. (Very far from an ideal design, of course). 

I think the search route/screen would be great. It could open with past searchers (log them down in the preferences?) instead of blank.

**Comment by vitorpamplona** [comment]
> This would not include doing different searches specific to the page the user is on, like finding a DM or chat room as you mentioned. So no new features, just rearranging the existing stuff.

The current search already offers DMs and ChatRooms.. so.. It would just be in a better place.

**Comment by maxmoney21m** [comment]
> Would you also move the x/x relay connection status? Are we ready for it? I think we still see too many little bugs and the status icon does let people know when something is wrong. (Very far from an ideal design, of course).

Here's an idea: do a kind of "signal bars" icon, without the numbers, as a first step to removing it. Of course I wouldn't want actual signal bars, but maybe something like @3j2009's relay icon with different number of relays filled in, or some other strong/weak/disconnected signal. The simplest would be a green/yellow/red notification dot.

If you think the number is important, then maybe we could at least shrink it somehow. If we don't shrink it or take the numbers away, adding the search bar is going to make the whole top bar look very crowded & uncomfortable.

**Comment by vitorpamplona** [comment]
This was done :)
