### ISSUE TITLE
Allow relay.nostr.band to be unsubscribed

### ISSUE THREAD

**Issue by h3zjp** [vitorpamplona/amethyst#311]
It would be nice if relay.nostr.band was hard-coded in "WIP. Add search with NIP-50 #167", forcing the user to connect to a relay they do not want.
Please stop forcing connections to unnecessary relays as some users do not use the search function!
(It is preferable to add it by default but allow the user to deactivate it.)

**Comment by vitorpamplona** [comment]
I need to see how to do this correctly because as we move more into NIP-65 and the Gossip model, the app is supposed to connect with many more relays than what the user declares as being used. To get notifications, for instance, the idea is to connect to as many relays as possible and download information about the author.

**Comment by h3zjp** [comment]
OK 👍

**Comment by frnandu** [comment]
Is the gossip model being developed now? Where can we discuss more details on gossip strategies?
