### ISSUE TITLE
Problem: copying note ID actually copies nevent<> rather than note<>

### ISSUE THREAD

**Issue by gazhayes** [vitorpamplona/amethyst#421]
**Problem:** copying note ID actually copies nevent<> rather than note<>

When users select `copy note ID` from the menu next to a note, what is copied to the clipboard is an `nevent` string rather than a `note` string.

**Solution:** copy `note` string instead. 

If this stays unfixed for a while I'll eventually send a PR, so if someone starts fixing this please comment that you are doing so.

**Comment by vitorpamplona** [comment]
So, both have the hex of the note. The nevent is just better because the receiving end of the URI can also see the event kind and preferred relay to find the event.

**Comment by gazhayes** [comment]
But people want to paste it into telegram etc to share the note, and most clients only work well with note1<...>

**Comment by vitorpamplona** [comment]
The problem is that other clients don't can't find the event with only a note1... If the receiving user has a relay set that is different than yours, it's likely it won't find the note. The nevent has the relay information so the client knows where to download the post. Let's hope other clients build support for it over time.
