### ISSUE TITLE
[UI] Create settings menu. Move private key from profile to settings. Move log out button. Add icons.

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#59]
Consider:
1. Consider moving the private key from profile page to npub + nsec section in newly created settings in menu. I am not sure what the need is to have easy accessibility to the private key. This might enable user mistakes.
2. Consider adding icons to the menu, example links below.
3. Consider moving log out from adjacent to other menu options to bottom left separate area to reduce risk of accidental log out.
4. Consider deleting followers / following in menu. This is already displayed on the profile page.

![Amethyst UI (1)](https://user-images.githubusercontent.com/64376233/216127155-223b5d35-2aaa-4a3a-ac4b-88eb6d85c7ab.png)

User feedback:
`"_Where I can find my private key?_"`
https://damus.io/note14ke7gc05dure4nrvu9hk2ulguszd652s0j2w57xlr8urvqd76xaszppw2l

Example icons from pixabay:
warning icon: https://pixabay.com/vectors/flat-design-symbol-icon-www-2126885/
exit icon: https://pixabay.com/vectors/exit-emergency-exit-door-way-sign-98584/
gear icon: https://pixabay.com/vectors/gear-transmission-settings-industry-1077563/

**Comment by braydonf** [comment]
Settings could also have:
- An option to enable/disable translation features and any other specifics.
- How link previews are handled (show/hide).
- Image, audio and video preview and loading options.
- Key management that can eventually support NIP-06 for backup of the key.

**Comment by maxmoney21m** [comment]
@vitorpamplona is anybody working on this already?

**Comment by vitorpamplona** [comment]
Way too many requests in a single issue. 

Let's start with the basics. We have to remove the private key button and add an option in the Drawer to Backup Account. A new screen pops up with instructions of what the private key is, where to store it (Password Manager) and then a button to make it visible or to copy to clipboard. 

We can reuse the same screen to display after a new user presses a "Generate New Key" in the login page.

**Comment by maxmoney21m** [comment]
@vitorpamplona Maybe it makes sense to go step by step, but I would like to know a little more what the long term plan is because that will make it easier to take steps in that specific direction. Eventually, I think we would want some kind of Settings screen (or maybe an Account Management screen e.g. #104) and the "Backup Account" option would be in there.

For now I agree the easiest step would be to add "Backup Account" to the drawer, but it seems a little too "in your face" to leave it there long term, especially since you only really need to do it once or very infrequently. Personally I would like a setting to enable biometric unlock for displaying the private key, and the private key backup button to be somewhat buried, or at least not right in the Drawer.

**Comment by vitorpamplona** [comment]
I agree with the biometric support to see the key. Maybe we should add it now already and activate it by default. 

I also agree that in the long term, it should not be there. But Backup and Settings are two different things. Backup doesn't fit in the general notion of Settings: it's not a setting. And backup will probably include other things in the future, especially if we add a lightning wallet to the app and will most likely feature detailed information on how to keep your account safe.

**Comment by vitorpamplona** [comment]
Looks like most of the issues here were addressed in different ways. I will close this post, but please open new ones for the issues you think remain open.
