### ISSUE TITLE
[BUG] Tagging Issue: App Crashes

### ISSUE THREAD

**Issue by crimsonleaf363** [vitorpamplona/amethyst#757]
**Describe the bug**
The app crashes when you try to tag "@" a user in a reply to a note.

**To Reproduce**
1. Select a note.
2. Tag "@" a user in a reply to the note.
3. The app crashes.

**Expected behavior**
A user is successfully tagged in a reply to a note.

**Device (please complete the following information):**
 - Android Version [e.g. 33]: GrapheneOS Android 14
 - App Version [e.g. v0.20.3]: v0.83.8

**Comment by vitorpamplona** [comment]
FYI, this seems to be an issue that only happens on the default keyboard of Graphene OS. Changing the keyboard fixes it. 

https://coracle.social/notes/nevent1qyt8wumn8ghj7un9d3shjtnddaehgu3wwp6kytcpzemhxue69uhkummnw3ezu7rdwgh8ymmrddej7qghwaehxw309aux6u3ww4ek2mn0wd68ytn0wfnj7qgewaehxw309aex2mrp0yhxummnw3exzarf9e3k7mf0qyv8wumn8ghj7cmp9ehhyctwvajhq6tvdshxgetk9uq3jamnwvaz7tmvd9nksarwd9hxwun9d3shjtnrdakj7qghwaehxw309amxjar0wghxummnw3erztnrdakj7qgawaehxw309ahx7um5wghx6at5d9h8jampd3kx2apwvdhk6tcpzemhxue69uhk2er9dchxummnw3ezumrpdejz7qgmwaehxw309aex2mrp0yhx7unpdenk2urfd3kzuer9wchsqgxhrqmlyasagpmc0hqzeuapzlalsprve560tmewt3zsp34p2u3j0q7cuy75

**Comment by vitorpamplona** [comment]
Florisboard also has the same issue. Anysoft, GBoard and Unexpected Keyboards seem to work.

**Comment by hax0rbana-adam** [comment]
Does anyone have any idea where in the code we should be looking to fix this? It wasn't a problem on older versions of Amethyst. It was promptly reported since tagging people is an extremely common operation. Probably introduced in 0.83.8 or 0.83.9? Possibly as far back as 0.83.7.

I'll try to grab a test phone and see if I can determine the exact release that introduced this issue and report back here with whatever I find.

**Comment by vitorpamplona** [comment]
It's not on our code. The stack trace doesn't know any particular issues that can be handled on our codebase. But if you want to take a look, it is a bug that happens when the [UrlUserTagTransformation](https://github.com/vitorpamplona/amethyst/blob/main/app/src/main/java/com/vitorpamplona/amethyst/ui/actions/UrlUserTagTransformation.kt) class is used. VisualTransformations map the `npub` to the user's name in the edit field, reducing the length of the text. The issue happens because some keyboards run their auto-correct procedures in the modified text but with indexes of the original text, which causes an OutOfBounds exception. 

Currently, the Alpha release of FlorisBoard has this issue fixed. OpenBoard and whatever Graphene uses as the default keyboard still have these issues. AnySoft, Unexpected Keyboard, and GBoard never crash.

**Comment by vitorpamplona** [comment]
This was solved on [v0.87.6](https://github.com/vitorpamplona/amethyst/releases/tag/v0.87.6)
